### ISSUE TITLE
CC przyrastające do pewnego poziomu - rozwiązanie na czas testów

### ISSUE THREAD

**Issue by mstrojny** [mstrojny/cp2#107]
od piratów? ze zdarzeń? na starcie?

**Comment by ghost** [comment]
update/wprowadzenie tak jak na starcie
zamiast zdarzen - ciagly minimalny doplyw ograniczony z gory (limit dla spiochow)

**Comment by mstrojny** [comment]
zmiana ccoinów (ale też po zakupie) daje event, żeby startowały czekające requesty

**Comment by mstrojny** [comment]
- jaki jest limit CCoinów dostępnych bezpośrednio - po uzgodnieniu kosztów
