### ISSUE TITLE
Rozjazd tabelek na ship_management.htm

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#112]
Do reprodukcji: stworzyć projekt okrętu bez uzbrojenia, efekt jak w linku:
https://drive.google.com/open?id=0B0URRvzTPhHmSGdMcjRvOU8tYzg

**Comment by mstrojny** [comment]
W linku jest apka a nie screen. to monitor na androida?

**Comment by Jacek-Siuda** [comment]
Zły link, już poprawiłem. Sorry, pierwotny link był linkiem do monitora, były obok siebie, musiałem źle kliknąć.

**Comment by mstrojny** [comment]
Na czym konkretnie polega rozjazd?

**Comment by Jacek-Siuda** [comment]
Zły alignment (UX). Poniżej Rocinante jest kolejny model, zepchnięty na dół przez Nathan Hale (który wyrównuje do uzbrojenia Roci). IMO Nathan Hale powinien być 2-3`<TR>` niżej, wtedy powinien się wyrównać z kolejnym modelem.

**Comment by mstrojny** [comment]
ok, to tak to layoutuje bootstrap, także od nas niezależne. próbowałem jakiś czas temu już patrzeć, czy da się to inaczej ułożyć, ale mi się nie udało. zamykam dopóki nie zobaczę działającego przykładu.
