### ISSUE TITLE
Złomowanie floty otwiera zły widok.

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#114]
Kosmetyczne.
Po złomowaniu floty wybranej z filtra planety otwiera się dziwny widok flot: 
- "Floty na planecie XXX"
- "Łączna liczba wszystkich flot: 0"
- brak boxa z flotami (to chyba OK, nie miałem tam żadnej aktywnej floty)
- widoczny box z wszystkimi grupami flot (nieobecnymi nad planetą)
- widoczny box flotami zadokowanymi (tylko tymi obecnymi "nad" planetą).

Reprodukcja:
Potrzebne dwie floty(?) nad planetą (obie zadokowane?)
Klikasz w planetę, wybierasz filtr "Floty|Przebywające"
Klikasz jedną z flot, wybierasz "Akcje|Złomuj wszystkie okręty"

**Comment by mstrojny** [comment]
Invalid, obecnie grupy flot pokazują się zawsze bez względu na filtr. Nie wiadomo, czy to będzie kiedyś zmienione.
