### ISSUE TITLE
Przejęta i porzucona planeta wciąż widnieje na spisie planet pierwotnego gracza.

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#116]
Jeżeli to specjalnie, to do zamknięcia.

W ramach wymuszania degradacji słabiej rozwiniętych metropolii nieaktywnego gracza zacząłem przejmować słabe prowincje i je porzucać. Po takim manewrze wciąż są widoczne na spisie planet gracza od którego je przejąłem (chociaż właścicielem są formalnie Regresjanie). Może ma to związek z tygodniowym limitem czasu, jak przy awansach na metropolie?

Tak BTW, możnaby się zastanowić, czy wogóle nie uprościć przejmowania nieaktywnych imperiów. Jak ktoś nie gra 4tyg+, raczej nie potrzebuje zwiększonej ochrony przed przejęciami...

**Comment by Jacek-Siuda** [comment]
Problem jest nawet bardziej złożony, część planet widnieje jako moja własność, mimo że je opuściłem...
Po kliknięciu na planetę mam właściciel: [ja], mimo że nie mam nad nią kontroli.

**Comment by mstrojny** [comment]
Do sprawdzenia

**Comment by Jacek-Siuda** [comment]
Kolejny update:
Na głównej stronie pojawia mi się komunikat z, jak przypuszczam, poprawną nazwą: "1m temu utraciłeś kontrolę nad planetą Regresjanie 5." Na mapie i liście planet wroga widoczna jest orginalna nazwa, chyba że zrobię skan - wtedy nazwa i właściciel się zmieniają na poprawne (chociaż ciągle widnieją na liście planet gracza od którego planetę przejąłem). Może to "random ficzer" FoW?

**Comment by Jacek-Siuda** [comment]
Kolejny efekt uboczny (źródło zapewne to samo) - Pomimo zrobienia skanu, nazwa planety nad którą stacjonuje nie zmieniła się (jest pierwotna) również w podglądzie floty. Np.:
```
Stacjonująca Zwiad 3
Pozycja [XXXX,YYYY,0]:[673,-821,167]   P2K4_2A1335A7
Oficjalne siły zbrojne planety
```
Na skanie jest:
```
Prowincja Regresjanie 5
Pozycja: [XXXX,YYYY,0]:[673,-821,167] 
```
P2K4_2A1335A7 nie mam na liście skrótów ani pozycji.
Do tego odnoszę wrażenie (ale twardych dowodów nie mam), że planety pod kontrolą Regresjan wciąż liczą się do limitu Prowincji powstrzymujących najsłabszą Metropolię przed degradacją.

**Comment by mstrojny** [comment]
Pierwsze dwa poprawione.
Skan jest obecnie warunkiem koniecznym zakutalizowania informacji - ficzer.
Stara nazwa przy koordynatach to dupliakat.
Fixed.
