### ISSUE TITLE
W zawiadomieniach o rozpoczęciu bitwy widnieją stare nazwy planet

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#117]
W zawiadomieniach e-mail o rozpoczęciu bitwy widnieją mi stare nazwy planet, pomimo, że dawno (1 miesiąc+) zmieniłem nazwy. Trochę dezorientujące.

Np.
email (niepoprawny): 
```
Sir, na pozycji [2291,2131,0]:[314,537,199] (P2KS_13A219C7) zostaliśmy znienacka napadnięci przez Piratów! Nie jest jasne z jakiej planety pochodzą, nowy raport wywiadu pomoże rozpoznać wroga.
```
Raport wojenny (poprawny):
```
Raport wojenny
2017/11/14 08:21

Bitwa na pozycji [2291,2131,0]:[314,537,199]   PeKaEs III zakończyła się naszym zwycięstwem. 
```

Trochę pachnie FoW.

**Comment by mstrojny** [comment]
duplikat zgłoszenia 111 https://waffle.io/mstrojny/cp2/cards/59c20a9d7076f3004d8db60f
