### ISSUE TITLE
Strona: "Kadra w grupie flot" podaje nieprawdziwe informacje.

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#151]
Reprodukcja:
1) Wejść do grupy flot (dowolny stan?)
2) Wybrać `Więcej->Dowódcy w te grupie`
W polu: ` Przebywa na XXX` podana jest (na moje oko) planeta powołania floty a nie obecna pozycja oficera.

Inny sposób:
1) Wejść na listę kadry
2) [opcjonalnie] Odfiltrować Pilotów
Tutaj planeta dla stacjonujących oficerów jest podana poprawnie, dla flot w ruchu wyświetlają się nieprawidłowe.

Jeżeli "tak miało być" to opis pola jest co najmniej mylący, może w ogóle nie pokazywać?

**Comment by mstrojny** [comment]
Tam jest planeta okrętowania i "tak miało być". Usunięcie też nie jest perfekcyjnym rozwiązaniem, bo przy opuszczaniu planety ta informacja znowu może być przydatna (nie można opuścić dopóki ktoś jest do niej przypisany). Dlatego to co jest zostaje jako mniejsze zło.

**Comment by Jacek-Siuda** [comment]
Hmm, przy opuszczaniu planety liczy się raczej wiedza kogo utrzymuje a nie kogo zaokrętowała? Mogę sprawdzić, czy stworzenie floty zapobiegnie opuszczeniu.
W każdym razie, jeżeli w dwóch różnych widokach w tym samym polu są wyświetlane rozbieżne dane, to z reguły jest to bug. Ale jak tam sobie chcesz. Ja z tej informacji nie korzystam, bo jest niewiarygodna.

**Comment by mstrojny** [comment]
Tak jak pisałem, dla pilotów podawana jest planeta na której ostatnio postawił stopę, dla tych bez zajęcia planeta gdzie jest fizycznie i nie ma tu sprzeczności. Zgodziłem się, że to nie jest idealne rozwiązanie. Od dawna więcej ludzi na to nie narzeka, więc temat jest odsunięty.
