### ISSUE TITLE
mapa - info o potrzebie scanu jesli jest mozliwy i potrzebny

### ISSUE THREAD

**Issue by ghost** [mstrojny/cp2#27]

**Comment by mstrojny** [comment]
hmm w pierwszym systemie to skan chyba automatycznie powinien się wykonywać jeśli to jedyny sposób na podanie informacji

**Comment by tmaliniak** [comment]
https://github.com/mstrojny/cp2/issues/27

**Comment by ghost** [comment]
z maila:

tak jak na planecie proponuje tekst typu:
"Pełne informacje o systemie możesz uzyskać "przysyłając tu flotę" (tu link) i skanując system."
(http://www.cosmopulse.net/beta/fleet/fleet_action_chooser.jsp?pos=[502,285,0]:[-604,-514,-53])

Ewentuanie dodać: "Możesz też zlecić wywiadowi "sporządzenie raportu" (link)."
(http://www.cosmopulse.net/beta/spy/choose_action_planet.htm)

A jak nie wiemy nic, to mozna by napisac dodatkowo cos w stylu "nie masz żadnej wiedzy o tym systemie"

**Comment by ghost** [comment]
dodane, bez informacji o wywiadzie bo nie mozna go ustawic na zadana planete
