### ISSUE TITLE
Nie zapisuje się nowa nazwa planety.

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#81]
Reprodukcja (100%) prosta: wchodzimy na planetę, klikamy `Zmień nazwę`, wpisujemy nową nazwę i klepiemy `Enter` - zostaje stara nazwa. 

Nazwa zmieni się tylko, jeśli zamiast `Enter` klikniemy ptaszka z boku.

Trochę to nieintuicyjne, pachnie złą obsługą domyślnej akcji formularza...

**Comment by mstrojny** [comment]
W takiej sytuacji - co się dzieje po przeładowaniu strony, jest stara czy nowa nazwa?

**Comment by Jacek-Siuda** [comment]
Po przeładowaniu zostaje stara, po przejściu od spisu planet też stara.
Nowa nazwa idzie zdaje się GETem, bo w pasku pojawia się: http://www.cosmopulse.net/gamma/planet/show_planet.htm?planetId=8418&name=foo

Co ciekawe, problem występuje wyłącznie na kompie domowym (Win10 + Fafox), a w robocie (Mint + Fafox) działa bez zarzutu....

**Comment by mstrojny** [comment]
Nie powtarza się u mnie, także na FF+Win. Tam jest ajax, adres się nie przeładowuje. Strzelam, że cache przeglądarki.
Na teraz works for me.

**Comment by mstrojny** [comment]
Ok, ujednoliciłem jednak rename z np. nazwą floty. Po updacie chyba jak gdzieś nie działało to powinno zacząć :)
