### ISSUE TITLE
Przebazowanie floty jednym kliknięciem.

### ISSUE THREAD

**Issue by Jacek-Siuda** [mstrojny/cp2#82]
[Enhancement] Konieczność rozwiązania floty w celu jej przebazowania nie wnosi nic do gry.

Przydałoby się dodać akcję `Zmień planetę macierzystą` dla powołanej floty.

**Comment by mstrojny** [comment]
Jaki jest praktyczny usecase kiedy chcemy zmienić planetę macierzystą floty, odkąd można wybrać dowolną planetę powołując nową flotę?

**Comment by Jacek-Siuda** [comment]
A nie miało być tak, że flota danej planety ma bonusy do jej obrony?

W takim razie jaki jest w ogóle praktyczny usecase przypisywania flot do planety? Nie prościej zrobić ograniczenie liczbowe (`nie będziesz miał więcej flot niż planet`).

W każdym razie przy wystawiania buga przeoczyłem możliwość przypisywania planety do floty w momencie jej tworzenia i że generalnie można już ignorować ten atrybut. ;)

Jeżeli uważasz, że tak jak jest, jest dobrze, to zamknij buga :)

**Comment by mstrojny** [comment]
Bonusy do obrony to jeden z pomysłów do wykorzystania tego przypisania na przyszłość. Ma to też sens fabularny. Zostawiamy sobie to przypisanie i wykorzystamy jak przyjdzie czas. Zamykam.
